### PR TITLE
Add python3-wheel to Docker package list

### PR DESCRIPTION
**Pull request by nkeukeleire**
python3-wheel required while building Docker

### CODE REVIEW

**Comment by GregoryVds** [comment]
Thanks for the patch!
Weird, it was building successfully 10 days ago. 
I am triggering a build on master right now to double check... hold on...

**Comment by GregoryVds** [comment]
Can you show me the logs you got when trying to build the Docker?
I just triggered a build on Master branch and Travis was able to build the Docker without this package.
See https://travis-ci.com/github/Tessares/libconvert/builds/181595284

**Comment by GregoryVds** [comment]
Ok logs are below, weird that the `docker build` does not exit with failure.
Seems we just need the Scapy lib, because tests are passing?
Anyway, let's merge this then :-) thanks

```
Step 8/8 : RUN pip3 install scapy
 ---> Running in faef45899a38
Collecting scapy
  Downloading https://files.pythonhosted.org/packages/c6/8f/438d4d0bab4c8e22906a7401dd082b4c0f914daf2bbdc7e7e8390d81a5c3/scapy-2.4.4.tar.gz (1.0MB)
Building wheels for collected packages: scapy
  Running setup.py bdist_wheel for scapy: started
  Running setup.py bdist_wheel for scapy: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9542klkb/scapy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-xyq4qebz --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for scapy
  Running setup.py clean for scapy
Failed to build scapy
Installing collected packages: scapy
  Running setup.py install for scapy: started
    Running setup.py install for scapy: finished with status 'done'
Successfully installed scapy-2.4.4
Removing intermediate container faef45899a38
 ---> a905f17cc21b
Successfully built a905f17cc21b
Successfully tagged tessares.net/libconvert:latest
`
```

**Review by GregoryVds — APPROVED** [review]

**Comment by matttbe** [comment]
@nkeukeleire please next time as the reason of a modification in your commit message to avoid the reviewer to try to guess it by looking at logs, etc. 😉

**Pull request merged**
